vulnman = "./configs/adhoc-nuclei.yml"

logfile =     "/var/log/vulnman_nuclei/logs/adhoc.ndjson"
results-dir = "/var/log/vulnman_nuclei/results/adhoc/"

# do it manually
no-update-templates = true
no-update-nuclei = true

# ad hoc scan => ad hoc targets in adhoc-nuclei.yml
dont-query-database = true

# this is not a scheduled scan
dont-mark-targets = true

# process results == create gitlab issues
dont-process-results = false