nuclei-config = "./configs/latest-nuclei.yml"

logfile =     "/var/log/vulnman_nuclei/logs/latest.ndjson"
results-dir = "/var/log/vulnman_nuclei/results/latest/"

# we scan everything
dont-query-database = false
all = true

# this is not a scheduled scan
dont-mark-targets = true