nuclei-conf = "./configs/latest-nuclei.yml"

logfile =     "/var/log/vulnman_nuclei/logs/latest.ndjson"
results-dir = "/var/log/vulnman_nuclei/results/latest/"

# we scan everything
dont-query-database = false
all = true

# this is not a scheduled scan
dont-mark-targets = true

# process results and report them to GitLab
dont-process-results = false

# https://gitlab.ics.muni.cz/dkb-zh/threats/findings-nuclei
gitlab-project-id = 6355

# Adam Ch. Andrej T.
assignee = "496,229"
