nuclei-conf = "./configs/scheduled-nuclei.yml"

logfile =     "/var/log/vulnman_nuclei/logs/scheduled.ndjson"
results-dir = "/var/log/vulnman_nuclei/results/scheduled/"

number-of-targets = 50

# https://gitlab.ics.muni.cz/dkb-zh/threats/findings-nuclei
gitlab-project-id = 6355

# Adam Ch. Andrej T.
assignee = "496,229"

exceptions = ["phpinfo-files", "error-logs", "shell-history", "apache-server-status", "htaccess-config", "cisco-telepresence", "ssh-known-hosts", "ds-store-file", "mikrotik-routeros-api", "mikrotik-ftp-server-detect", "eset-protect-panel", "squirrelmail-login"]
