nuclei-config = "./configs/scheduled-nuclei.yml"

logfile =     "/var/log/vulnman_nuclei/logs/scheduled.ndjson"
results-dir = "/var/log/vulnman_nuclei/results/scheduled/"

number-of-targets = 50

gitlab-project-id = 1234

# User A, User B, User C
assignee = "1111,2222,3333"

exceptions = ["phpinfo-files", "error-logs", "shell-history", "apache-server-status", "htaccess-config", "cisco-telepresence", "ssh-known-hosts", "ds-store-file", "mikrotik-routeros-api", "mikrotik-ftp-server-detect", "eset-protect-panel", "squirrelmail-login"]
